config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  root "static_pages#home"
  resources :books, only: [:index, :show] do
    resources :reviews
  end
  namespace :admin do
    resources :books
    resources :users, only: [:show, :index, :destroy]
  end
  resources :users, only: :show
  resources :comments, only: [:create, :update, :destroy]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize user, namespace
    user ||= User.new
    if user.is_admin?
      can :manage, :all
    else
      if namespace == "admin"
        cannot :manage, :all
      end   
      can :read, :all
      can :manage, Review do |review|
        review.user == user
      end  
      can :manage, Comment do |comment|
        comment.user == user
      end
    end
  end
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :like_activities, dependent: :destroy

  belongs_to :user
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :user_books, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :users, through: :user_books

  belongs_to :category

  validates :title, presence: true, uniqueness: true, length: {maximum: 140}
  validates :author, presence: true, length: {maximum: 50}
  validates :number_of_pages, presence: true, numericality: {only_integer: true}, 
    length: {maximum: 5}
  enum rating: {zero_star: 0, one_star: 1, two_star: 2, three_star: 3, 
    four_star: 4, five_star: 5}
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :review
  has_many :sub_comments, class_name: "Comment", foreign_key: "parent_id",
    dependent: :destroy
  belongs_to :parent_comment, class_name: "Comment"
end

app/models/like_activity.rb
class LikeActivity < ActiveRecord::Base
  belongs_to :user
  belongs_to :activity
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: User.name
  belongs_to :followed, class_name: User.name
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
  has_many :comments, dependent: :destroy

  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: "follower_id",
    dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: "followed_id",
    dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :like_activities, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :user_books, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :books, through: :user_books

  has_attached_file :avatar, styles: {medium: "300x300>", 
    thumb: "100x100#"}, default_url: "/images/:style/cute.jpg"
    
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/user_book.rb
class UserBook < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  load_and_authorize_resource
  before_action :load_categories, only: [:new, :edit]

  def new
  end

  def create
    if @book.save
      flash[:success] = t "book.create_notice"
      redirect_to admin_book_path @book
    else 
      load_categories
      render :new
    end
  end

  def show
  end

  def edit
  end

  def index
    load_categories
    @q = @books.ransack params[:q]
    @books = @q.result.page params[:page]
  end  

  def destroy
    if @book.destroy
      flash[:success] = t "book.destroy"
    else 
      flash.new[:danger] = t "book.destroy_alert"
    end
    redirect_to admin_books_path
  end

  def update
    if @book.update book_params
      flash[:success] = t "book.update_notice"
      redirect_to admin_book_path @book
    else
      load_categories
      render :edit
    end
  end

  private
  def book_params
    params.require(:book).permit :title, :author, :category_id, 
      :number_of_pages, :publish_date
  end

  def load_categories
    @categories = Category.all
    @category_selects = @categories.collect {|category| [category.name, category.id]}
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = @users.page params[:page]
  end

  def show    
  end

  def destroy
    if @user.destroy
      flash[:success] = t "user.destroy"
    else
      flash[:dager] = t "user.destroy_fail"
    end
    redirect_to admin_users_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  rescue_from ActiveRecord::RecordNotFound do
    flash[:notice] = t "application.nil", column_name: params[:id]
    redirect_to root_url
  end

  private
  def current_ability
    namespace = controller_path.split("/").first
    Ability.new current_user, namespace
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  load_and_authorize_resource

  def show
    @review ||= current_user.reviews.new
    @comment = current_user.comments.new
  end

  def index
    load_categories
    @q = @books.ransack params[:q]
    @books = @q.result.page params[:page]
  end

  def load_categories
    @categories = Category.all
    @category_selects = @categories.collect {|category| [category.name,
      category.id]}
    @rating_selects = Book.ratings.map {|key,value| [t("rate.#{key}"),value]}
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build comment_params
    @review = Review.find @comment.review_id unless 
      comment_params[:review_id].nil?
    byebug
    unless @comment.save
      flash[:danger] = "Fail"
    end
    redirect_to root_url
  end

  def destroy
    #do destroy
  end
  
  private
  def comment_params
    params.require(:comment).permit :content, :review_id, :parent_id
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  load_and_authorize_resource
  
  def create
    if @review.save
      flash[:success] = t "review.thanks"
    else
      flash[:danger] = t "review.wrong"
    end
    redirect_to :back
  end

  def edit
  end

  def update
    if @review.update review_params
      flash[:success] = t "review.update-success"
    else
      flash[:danger] = t "review.update-fail"
    end
    redirect_to :back
  end

  def destroy
    if @review.destroy 
      flash[:success] = t "review.destroy-success"
    else
      flash[:danger] = t "review.destroy-fail"
    end
    redirect_to :back
  end

  private
  def review_params
    params.require(:review).permit :content, :book_id, :user_id
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_account_update_params, only: :update

  protected
  def configure_account_update_params
    devise_parameter_sanitizer.permit :account_update, keys: [:name, :password, 
      :password_confirmation, :avatar, :current_password]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/books/_book.html.erb
<div class="item col-xs-4 col-lg-4">
  <div class="thumbnail">
    <%= link_to (image_tag t("application.default-image"), 
      class: "group list-group-image mc-img"), book %>
    <div class="caption">
      <h4 class="group inner list-group-item-heading">
        <%= link_to book.title, [:admin, book] %>
      </h4>
      <p class="group inner list-group-item-text">
        <%= t "book.book_author" %>: <%= book.author %>
      </p>
      <p class="group inner list-group-item-text">
        <%= t "book.book_category" %>: <%= book.category.name %>
      </p>
      <p>
        <%= link_to t("book.edit"), edit_admin_book_path(book), 
          class: "btn btn-primary" %>
        <%= link_to t("book.delete"), admin_book_path(book), 
          method: :delete, data: {confirm: t("application.confirm")}, 
          class: "btn btn-primary" %>
      </p>
    </div>
  </div>
</div>

app/views/admin/books/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @book] do |f| %>
      <%= render "shared/error_messages", object: @book %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :author %>
        <%= f.text_field :author, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :category_id %>
        <%= f.select :category_id, @category_selects, {}, 
          class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :number_of_pages %>
        <%= f.text_field :number_of_pages, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :publish_date %>
        <%= f.date_field :publish_date, class: "form-control" %> 
      </div>
      <div class="action center">
        <%= f.submit t("book.#{params[:action]}"), class: "btn btn-md btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/books/edit.html.erb
<%= provide :title, t("book.edit") %>
<h1><%= t "book.edit" %></h1>
<%= render "form" %>

app/views/admin/books/index.html.erb
<% provide :title, t("book.books") %>
<h1><%= t "book.books" %></h1>  
<div class="search-books">
  <%= render "shared/form_search_books" %> 
</div>  
<div class="list_books">
  <div class="books">
    <%= render @books %>
  </div>
  <div class="clear">
    <%= paginate @books %>
  </div>
</div>

app/views/admin/books/new.html.erb
<%= provide :title, t("book.new") %>
<h1><%= t "book.new" %></h1>
<%= render "form" %>

app/views/admin/books/show.html.erb
<%= provide :title, @book.title %>
<div class="row">
  <div class="col-md-4">
    <div class="book-image center">
      <%= image_tag t("application.default-image"), class: "mc-img" %>
    </div>
    <div class="book_info">
      <div class="produdct_name center">
        <p><%= @book.title %></p>
      </div>
      <p>
        <%= t "book.book_author" %>:
        <%= @book.author %>
      </p>
      <p>
        <%= t "book.book_category" %>:
        <%= @book.category.name %>
      </p>
      <p>
        <%= t "book.pages" %>:
        <%= @book.number_of_pages %>
      </p>
      <p>
        <%= t "book.publish_date" %>:
        <%= @book.publish_date %>
      </p>
      <div class="center">
        <%= link_to t("book.edit"), edit_admin_book_path(@book), 
          class: "btn btn-primary" %>
        <%= link_to t("book.delete"), admin_book_path(@book), 
          method: :delete, data: {confirm: t("application.confirm")}, 
          class: "btn btn-danger" %>
      </div>
    </div>
  </div>
  <div class="col-md-8 review-zone">
    <h2><%= t "book.review" %></h2>
  </div>
</div>

app/views/admin/users/_user.html.erb
<div class="item col-xs-4 col-lg-4 testdiv">
  <div class="profile-userpic center">
    <%= image_tag user.avatar.url :thumb %>
  </div>
  <div class="profile-usertitle">
    <div class="profile-usertitle-name">
      <%= link_to user.name, admin_user_path(user) %>
    </div>
    <div class="profile-usertitle-email">
      <%= user.email %>
    </div>
    <div class="profile-userbuttons">
      <%= link_to t("application.destroy"), admin_user_path(user), 
        method: :delete, data: {confirm: t("application.confirm")},
        class: "btn btn-danger btn-sm" %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<% provide :title, t("user.users") %>
<div class="col-md-9 col-md-offset-3">
  <h1><%= t "user.users" %></h1>
  <%= render @users %>
  <div class="clear">
    <%= paginate @users %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row profile">
    <div class="col-md-3">
      <div class="profile-sidebar">
        <div class="profile-userpic center">
          <%= image_tag @user.avatar.url :thumb %>
        </div>
        <div class="profile-usertitle">
          <div class="profile-usertitle-name">
            <%= @user.name %>
          </div>
          <div class="profile-usertitle-email">
            <%= @user.email %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <div class="profile-content">
      </div>
    </div>
  </div>
</div>

app/views/books/_book.html.erb
<div class="item col-xs-4 col-lg-4">
  <div class="thumbnail">
    <%= link_to (image_tag t("application.default-image"), 
      class: "group list-group-image mc-img"), book %>
    <div class="caption">
      <h4 class="group inner list-group-item-heading">
        <%= link_to book.title, book %>
      </h4>
      <p class="group inner list-group-item-text">
        <%= t "book.book_author" %>: <%= book.author %>
      </p>
      <p class="group inner list-group-item-text">
        <%= t "book.book_category" %>: <%= book.category.name %>
      </p>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% provide :title, t("book.books") %>
<h1><%= t "book.books" %></h1>
<div class="search-books">
  <%= render "shared/form_search_books" %> 
</div>  
<div class="list_books">
  <div class="books">
    <%= render @books %>
  </div>
  <div class="clear">
    <%= paginate @books %>
  </div>
</div>

app/views/books/show.html.erb
<%= provide :title, @book.title %>
<div class="row">
  <div class="col-md-4">
    <div class="book_image">
      <p>
        <%= image_tag t("application.default-image"), class: "mc-img" %>
      </p>
    </div>
    <div class="book_info">
      <p><h4><%= @book.title %></h4></p>
      <p>
        <%= t "book.book_author" %>: 
        <%= @book.author %>
      </p>
      <p>
        <%= t "book.book_category" %>:
        <%= @book.category.name %>
      </p>
    </div>
  </div>
  <div class="review-zone col-md-8">
    <h1><%= t "book.review" %></h1>

    <div class="review-content">
      <% if @book.reviews.any? %>
        <%= render @book.reviews%>
      <% end %>

      <%= render "reviews/form" %>
    </div>
  </div>
</div>

app/views/comments/_comment.html.erb
<li id="comment-<%= comment.id %>">
  <span class="user">
    <%= link_to comment.user.name, comment.user %>:
    <%= comment.content %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words comment.created_at %> ago.
  </span>
  <span class="comment">
      <% if comment.sub_comments.any?%>
        <%= render comment.sub_comments %>
      <% end %>
  </span>
  <span class="comment-form">
    <% if comment.parent_comment.nil? %>
        <%= form_for @comment, url: comments_path do |f|%>
          <%= f.text_field :content %>
          <%= f.hidden_field :parent_id, value: comment.id %>
          <%= f.submit "Comment" %>
        <% end %>
    <% end %>
  </span>
</li>

app/views/users/show.html.erb
<div class="container">
  <div class="row profile">
    <div class="col-md-3">
      <div class="profile-sidebar">
        <div class="profile-userpic center">
          <%= image_tag @user.avatar.url :thumb %>
        </div>
        <div class="profile-usertitle">
          <div class="profile-usertitle-name">
            <%= @user.name %>
          </div>
          <div class="profile-usertitle-email">
            <%= @user.email %>
          </div>
        </div>
        <div class="profile-userbuttons">
          <%= button_to t("application.follow"), "#", 
            class: "btn btn-success btn-sm" %>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <div class="profile-content">
      </div>
    </div>
  </div>
</div>