config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  root "static_pages#home"
  resources :books, only: [:index, :show] do
    resources :reviews
  end
  namespace :admin do
    resources :books
    resources :users, only: [:show, :index, :destroy]
  end
  resources :users, only: :show
  resources :comments, only: [:create, :update, :destroy]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize user, namespace
    user ||= User.new
    if user.is_admin?
      can :manage, :all
    else
      if namespace == "admin"
        cannot :manage, :all
      end   
      can :read, :all
      can :manage, Review do |review|
        review.user == user
      end  
      can :manage, Comment do |comment|
        comment.user == user
      end
    end
  end
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :like_activities, dependent: :destroy

  belongs_to :user
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :user_books, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :users, through: :user_books

  belongs_to :category

  validates :title, presence: true, uniqueness: true, length: {maximum: 140}
  validates :author, presence: true, length: {maximum: 50}
  validates :number_of_pages, presence: true, numericality: {only_integer: true}, 
    length: {maximum: 5}
  enum rating: {zero_star: 0, one_star: 1, two_star: 2, three_star: 3, 
    four_star: 4, five_star: 5}
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :review
  has_many :sub_comments, class_name: "Comment", foreign_key: "parent_id",
    dependent: :destroy
  belongs_to :parent_comment, class_name: "Comment"
end

app/models/like_activity.rb
class LikeActivity < ActiveRecord::Base
  belongs_to :user
  belongs_to :activity
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: User.name
  belongs_to :followed, class_name: User.name
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
  has_many :comments, dependent: :destroy

  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: "follower_id",
    dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: "followed_id",
    dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :like_activities, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :user_books, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :books, through: :user_books

  has_attached_file :avatar, styles: {medium: "300x300>", 
    thumb: "100x100#"}, default_url: "/images/:style/cute.jpg"
    
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/user_book.rb
class UserBook < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  load_and_authorize_resource
  before_action :load_categories, only: [:new, :edit]

  def new
  end

  def create
    if @book.save
      flash[:success] = t "book.create_notice"
      redirect_to admin_book_path @book
    else 
      load_categories
      render :new
    end
  end

  def show
  end

  def edit
  end

  def index
    load_categories
    @q = @books.ransack params[:q]
    @books = @q.result.page params[:page]
  end  

  def destroy
    if @book.destroy
      flash[:success] = t "book.destroy"
    else 
      flash.new[:danger] = t "book.destroy_alert"
    end
    redirect_to admin_books_path
  end

  def update
    if @book.update book_params
      flash[:success] = t "book.update_notice"
      redirect_to admin_book_path @book
    else
      load_categories
      render :edit
    end
  end

  private
  def book_params
    params.require(:book).permit :title, :author, :category_id, 
      :number_of_pages, :publish_date
  end

  def load_categories
    @categories = Category.all
    @category_selects = @categories.collect {|category| [category.name, category.id]}
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = @users.page params[:page]
  end

  def show    
  end

  def destroy
    if @user.destroy
      flash[:success] = t "user.destroy"
    else
      flash[:dager] = t "user.destroy_fail"
    end
    redirect_to admin_users_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  rescue_from ActiveRecord::RecordNotFound do
    flash[:notice] = t "application.nil", column_name: params[:id]
    redirect_to root_url
  end

  private
  def current_ability
    namespace = controller_path.split("/").first
    Ability.new current_user, namespace
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  load_and_authorize_resource

  def show
    @review ||= current_user.reviews.new
    @comment = current_user.comments.new
  end

  def index
    load_categories
    @q = @books.ransack params[:q]
    @books = @q.result.page params[:page]
  end

  def load_categories
    @categories = Category.all
    @category_selects = @categories.collect {|category| [category.name,
      category.id]}
    @rating_selects = Book.ratings.map {|key,value| [t("rate.#{key}"),value]}
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build comment_params
    @review = Review.find @comment.review_id unless 
      comment_params[:review_id].nil?
    byebug
    unless @comment.save
      flash[:danger] = "Fail"
    end
    redirect_to root_url
  end

  def destroy
    #do destroy
  end
  
  private
  def comment_params
    params.require(:comment).permit :content, :review_id, :parent_id
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  load_and_authorize_resource
  
  def create
    if @review.save
      flash[:success] = t "review.thanks"
    else
      flash[:danger] = t "review.wrong"
    end
    redirect_to :back
  end

  def edit
  end

  def update
    if @review.update review_params
      flash[:success] = t "review.update-success"
    else
      flash[:danger] = t "review.update-fail"
    end
    redirect_to :back
  end

  def destroy
    if @review.destroy 
      flash[:success] = t "review.destroy-success"
    else
      flash[:danger] = t "review.destroy-fail"
    end
    redirect_to :back
  end

  private
  def review_params
    params.require(:review).permit :content, :book_id, :user_id
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/reviews/_form.html.erb
<%= form_for [@book, @review] do |f| %>
  <div class= "panel panel-default">
    <div class="panel-heading">
      <b><%= t "review.label" %></b>
    </div>
    <div class="panel-body">
      <%= f.hidden_field :book_id, value: @book.id %>
      <%= f.hidden_field :user_id, value: @current_user.id %>
      <%= f.text_field :content, rows: 1, class: "form form-group form-control" %>
    </div>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
      <div class="row">
        <div class="col-md-3">
          <small><%= review.user.name %></small>
        </div>
        <% if current_user == review.user %>
          <div class="col-md-2 col-md-offset-5">
          <%= link_to t("btn.edit"), edit_book_review_path(@book, review.id),
            class: "btn btn-xs btn-primary" %>
        <%= link_to t("btn.delete"), book_review_path(@book, review.id),
            method: :delete, data: {confirm: t("application.confirm")},
            class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="panel-body">
      <%= review.content %>
    </div>
    <div>
      <span class="comments">
        <% if review.comments.any? %>
          <%= render review.comments %>
        <% end %>
      </span>
      <span class="comment-form">
         <%= form_for @comment, url: comments_path do |f|%>
           <%= f.text_field :content %>
           <%= f.hidden_field :review_id, value: review.id %>
           <%= f.submit "Comment" %>
         <% end %>
      </span>
    </div>
</div>

app/views/reviews/edit.html.erb
<%= form_for [@book, @review], url: book_review_path, method: :put do |f| %>
  <div class= "panel panel-default">
    <div class="panel-heading">
      <b><%= t "review.label" %></b>
    </div>
    <div class="panel-body">
      <%= f.hidden_field :book_id, value: @review.book.id %>
      <%= f.hidden_field :user_id, value: @review.user.id %>
      <%= f.text_field :content, rows: 1, class: "form form-group form-control" %>
    </div>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide :title, t("application.home") %>
<div class="center jumbotron home">
  <h1><%= t "application.welcome" %></h1>
  <p><%= t "quote.first" %></p>
</div>